<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ElectroCell.Domain\ElectroCell.Domain.csproj" />
    <ProjectReference Include="..\ElectroCell.Infrastructure\ElectroCell.Infrastructure.csproj" />
  </ItemGroup>
</Project>
